### ISSUE TITLE
도메인 생성 오류

### ISSUE THREAD

**Issue by zzu-yaaa** [IAM-TEAM/IAM-BE#1]
원래 브랜치에 만들어서 pr 올리려고 했는데 브랜치 꼬이는 바람에
브랜치 삭제하고 일단 메인에 올렸습니다 ,,

![image](https://github.com/IAM-TEAM/IAM-BE/assets/110540359/5da43b0b-5b81-4ba8-b56d-dd13ebef229c)
(엔티티로 테이블 생성 후 추출한 ERD)

엔티티로 테이블 생성하고 ERD 추출한 결과
1. 에피소드 테이블 생성 안됨
2. 카테고리:채널이 1:N으로 연결되는 이슈 발생!

사소한 실수일 수 있겠지만 검토 부탁 ^.^
감삼당

**Comment by ManchanTime** [comment]
확인  완료.
limit은 SQL에서 이미 있는 명령어로 칼럼이름으로 사용하면 안됩니다.
ManyToOne 또는 OneToOne 관계는 fetch LAZY로 설정해야 합니다.
